<div id="login" tabindex="-1" role="dialog" aria-labelledby="login" aria-hidden="true" class="modal fade">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">

			<div class="modal-header">

				<button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">&times;</span></button>

				<h4 class="modal-title">Login</h4>

			</div>

			<div class="modal-body">

				<form action="/user/login" method="POST">

					<div class="form-group">
						<label>Username</label>
						<input name="username" type="text" placeholder="Derpinstein" class="form-control"/>
					</div>

					<div class="form-group">
						<label>Password</label>
						<input name="password" type="password" placeholder="Oooh Soo Secret" class="form-control"/>
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-block btn-primary">Login</button>
					</div>

				</form>

			</div>

		</div>
	</div>
</div>