<nav class="navbar navbar-default">

	<div class="container-fluid">

		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<a class="navbar-brand" href="/">Pipeline</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse">

				<ul class="nav navbar-nav nav-tabs">
					<li><a href="<?=$this->url(
					['controller'=>'guestbook'],
					'default',
					true) ?>">Guestbook</a></li>

				</ul>

			<? if( array_key_exists('user', $_SESSION) ): ?>

				<p class="navbar-text navbar-right">Signed in as <a href="#" class="navbar-link"><?=$_SESSION['user']['username'] ?></a> <a href="/user/logout" title="Log Out">Log Out</a></p>


			<? else: ?>

				<button type="button" class="btn btn-default navbar-btn navbar-right" data-toggle="modal" data-target="#login">Log In</button>
			<? endif ?>

		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>