<?=$this->doctype() ?>
<html>
	<head>
		<title>Pipeline</title>

		<!-- Viewport mobile tag for sensible mobile support -->
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<script type="text/javascript">
			var global = {};
			var classes = {};
		</script>

		<script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
		<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

	<? if(array_key_exists('user',$_SESSION) && $_SESSION['user']['theme']): ?>
		<link rel="stylesheet" href="https://bootswatch.com/<?=$_SESSION['user']['theme'] ?>/bootstrap.min.css">

	<? else: ?>
		<link rel="stylesheet" href="https://bootswatch.com/paper/bootstrap.min.css">

	<? endif ?>

		<!--STYLES-->
		<!--STYLES END-->

	</head>

	<body>

		<?=$this->partial('/partials/nav.phtml'); ?>
		<?=$this->partial('/partials/messages.phtml'); ?>
		<? if(error_get_last()): ?>
		<pre><?=var_dump(error_get_last()) ?></pre>
		<? endif ?>

		<?=$this->layout()->content ?>


		<?=$this->partial('/partials/footer.phtml'); ?>

		<!--SCRIPTS-->
		<!--SCRIPTS END-->

	</body>
</html>